/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GradesGradeKeyRouteImport } from './routes/grades.$gradeKey'
import { Route as ApiRpcRouteImport } from './routes/api/rpc'
import { Route as ApiChatbotRouteImport } from './routes/api/chatbot'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedBundlesRouteImport } from './routes/_authenticated/bundles'
import { Route as AuthenticatedBooksRouteImport } from './routes/_authenticated/books'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPaymentSubmitRouteImport } from './routes/api/payment.submit'
import { Route as ApiPaymentReviewRouteImport } from './routes/api/payment.review'
import { Route as AuthenticatedPracticeMistakesRouteImport } from './routes/_authenticated/practice.mistakes'
import { Route as AuthenticatedPaymentsNewRouteImport } from './routes/_authenticated/payments.new'
import { Route as AuthenticatedHomeworkHomeworkIdRouteImport } from './routes/_authenticated/homework.$homeworkId'
import { Route as AuthenticatedExamsExamIdRouteImport } from './routes/_authenticated/exams.$examId'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses.$courseId'
import { Route as AuthenticatedBooksBookIdRouteImport } from './routes/_authenticated/books.$bookId'
import { Route as AuthenticatedAdminWalletRouteImport } from './routes/_authenticated/admin.wallet'
import { Route as AuthenticatedAdminViewingRouteImport } from './routes/_authenticated/admin.viewing'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminStudentResultsRouteImport } from './routes/_authenticated/admin.student-results'
import { Route as AuthenticatedAdminSiteContentRouteImport } from './routes/_authenticated/admin.site-content'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRechargeCodesRouteImport } from './routes/_authenticated/admin.recharge-codes'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin.questions'
import { Route as AuthenticatedAdminQnaRouteImport } from './routes/_authenticated/admin.qna'
import { Route as AuthenticatedAdminPersonalExamsRouteImport } from './routes/_authenticated/admin.personal-exams'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminLoginAuditRouteImport } from './routes/_authenticated/admin.login-audit'
import { Route as AuthenticatedAdminLessonsRouteImport } from './routes/_authenticated/admin.lessons'
import { Route as AuthenticatedAdminLecturesRouteImport } from './routes/_authenticated/admin.lectures'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminHomeworkRouteImport } from './routes/_authenticated/admin.homework'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin.exams'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminCentersRouteImport } from './routes/_authenticated/admin.centers'
import { Route as AuthenticatedAdminBundlesRouteImport } from './routes/_authenticated/admin.bundles'
import { Route as AuthenticatedAdminBooksRouteImport } from './routes/_authenticated/admin.books'
import { Route as AuthenticatedAdminBookOrdersRouteImport } from './routes/_authenticated/admin.book-orders'
import { Route as AuthenticatedAdminAssistantsRouteImport } from './routes/_authenticated/admin.assistants'
import { Route as AuthenticatedAdminAssessmentsRouteImport } from './routes/_authenticated/admin.assessments'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAiFaqRouteImport } from './routes/_authenticated/admin.ai-faq'
import { Route as AuthenticatedExamsExamIdResultRouteImport } from './routes/_authenticated/exams.$examId.result'
import { Route as AuthenticatedAdminStudentsStudentIdRouteImport } from './routes/_authenticated/admin.students.$studentId'
import { Route as AuthenticatedAdminQuestionsNewRouteImport } from './routes/_authenticated/admin.questions.new'
import { Route as AuthenticatedAdminHomeworkNewRouteImport } from './routes/_authenticated/admin.homework.new'
import { Route as AuthenticatedAdminHomeworkHomeworkIdRouteImport } from './routes/_authenticated/admin.homework.$homeworkId'
import { Route as AuthenticatedAdminExamsNewRouteImport } from './routes/_authenticated/admin.exams.new'
import { Route as AuthenticatedAdminExamsExamIdRouteImport } from './routes/_authenticated/admin.exams.$examId'
import { Route as AuthenticatedAdminCoursesCourseIdRouteImport } from './routes/_authenticated/admin.courses.$courseId'
import { Route as AuthenticatedCoursesCourseIdLessonsLessonIdRouteImport } from './routes/_authenticated/courses.$courseId.lessons.$lessonId'
import { Route as AuthenticatedCoursesCourseIdLecturesLectureIdRouteImport } from './routes/_authenticated/courses.$courseId.lectures.$lectureId'
import { Route as AuthenticatedAdminExamsExamIdAttemptsAttemptIdRouteImport } from './routes/_authenticated/admin.exams.$examId.attempts.$attemptId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesGradeKeyRoute = GradesGradeKeyRouteImport.update({
  id: '/grades/$gradeKey',
  path: '/grades/$gradeKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcRoute = ApiRpcRouteImport.update({
  id: '/api/rpc',
  path: '/api/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatbotRoute = ApiChatbotRouteImport.update({
  id: '/api/chatbot',
  path: '/api/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBundlesRoute = AuthenticatedBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBooksRoute = AuthenticatedBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPaymentSubmitRoute = ApiPaymentSubmitRouteImport.update({
  id: '/api/payment/submit',
  path: '/api/payment/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentReviewRoute = ApiPaymentReviewRouteImport.update({
  id: '/api/payment/review',
  path: '/api/payment/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPracticeMistakesRoute =
  AuthenticatedPracticeMistakesRouteImport.update({
    id: '/practice/mistakes',
    path: '/practice/mistakes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsNewRoute =
  AuthenticatedPaymentsNewRouteImport.update({
    id: '/payments/new',
    path: '/payments/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeworkHomeworkIdRoute =
  AuthenticatedHomeworkHomeworkIdRouteImport.update({
    id: '/homework/$homeworkId',
    path: '/homework/$homeworkId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsExamIdRoute =
  AuthenticatedExamsExamIdRouteImport.update({
    id: '/$examId',
    path: '/$examId',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedCoursesRoute,
  } as any)
const AuthenticatedBooksBookIdRoute =
  AuthenticatedBooksBookIdRouteImport.update({
    id: '/$bookId',
    path: '/$bookId',
    getParentRoute: () => AuthenticatedBooksRoute,
  } as any)
const AuthenticatedAdminWalletRoute =
  AuthenticatedAdminWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminViewingRoute =
  AuthenticatedAdminViewingRouteImport.update({
    id: '/viewing',
    path: '/viewing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentResultsRoute =
  AuthenticatedAdminStudentResultsRouteImport.update({
    id: '/student-results',
    path: '/student-results',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSiteContentRoute =
  AuthenticatedAdminSiteContentRouteImport.update({
    id: '/site-content',
    path: '/site-content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRechargeCodesRoute =
  AuthenticatedAdminRechargeCodesRouteImport.update({
    id: '/recharge-codes',
    path: '/recharge-codes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQnaRoute = AuthenticatedAdminQnaRouteImport.update({
  id: '/qna',
  path: '/qna',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPersonalExamsRoute =
  AuthenticatedAdminPersonalExamsRouteImport.update({
    id: '/personal-exams',
    path: '/personal-exams',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLoginAuditRoute =
  AuthenticatedAdminLoginAuditRouteImport.update({
    id: '/login-audit',
    path: '/login-audit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLessonsRoute =
  AuthenticatedAdminLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLecturesRoute =
  AuthenticatedAdminLecturesRouteImport.update({
    id: '/lectures',
    path: '/lectures',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomeworkRoute =
  AuthenticatedAdminHomeworkRouteImport.update({
    id: '/homework',
    path: '/homework',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCentersRoute =
  AuthenticatedAdminCentersRouteImport.update({
    id: '/centers',
    path: '/centers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBundlesRoute =
  AuthenticatedAdminBundlesRouteImport.update({
    id: '/bundles',
    path: '/bundles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBooksRoute = AuthenticatedAdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBookOrdersRoute =
  AuthenticatedAdminBookOrdersRouteImport.update({
    id: '/book-orders',
    path: '/book-orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssistantsRoute =
  AuthenticatedAdminAssistantsRouteImport.update({
    id: '/assistants',
    path: '/assistants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssessmentsRoute =
  AuthenticatedAdminAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiFaqRoute = AuthenticatedAdminAiFaqRouteImport.update({
  id: '/ai-faq',
  path: '/ai-faq',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedExamsExamIdResultRoute =
  AuthenticatedExamsExamIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => AuthenticatedExamsExamIdRoute,
  } as any)
const AuthenticatedAdminStudentsStudentIdRoute =
  AuthenticatedAdminStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedAdminStudentsRoute,
  } as any)
const AuthenticatedAdminQuestionsNewRoute =
  AuthenticatedAdminQuestionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminQuestionsRoute,
  } as any)
const AuthenticatedAdminHomeworkNewRoute =
  AuthenticatedAdminHomeworkNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminHomeworkRoute,
  } as any)
const AuthenticatedAdminHomeworkHomeworkIdRoute =
  AuthenticatedAdminHomeworkHomeworkIdRouteImport.update({
    id: '/$homeworkId',
    path: '/$homeworkId',
    getParentRoute: () => AuthenticatedAdminHomeworkRoute,
  } as any)
const AuthenticatedAdminExamsNewRoute =
  AuthenticatedAdminExamsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)
const AuthenticatedAdminExamsExamIdRoute =
  AuthenticatedAdminExamsExamIdRouteImport.update({
    id: '/$examId',
    path: '/$examId',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIdRoute =
  AuthenticatedAdminCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedCoursesCourseIdLessonsLessonIdRoute =
  AuthenticatedCoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthenticatedCoursesCourseIdRoute,
  } as any)
const AuthenticatedCoursesCourseIdLecturesLectureIdRoute =
  AuthenticatedCoursesCourseIdLecturesLectureIdRouteImport.update({
    id: '/lectures/$lectureId',
    path: '/lectures/$lectureId',
    getParentRoute: () => AuthenticatedCoursesCourseIdRoute,
  } as any)
const AuthenticatedAdminExamsExamIdAttemptsAttemptIdRoute =
  AuthenticatedAdminExamsExamIdAttemptsAttemptIdRouteImport.update({
    id: '/attempts/$attemptId',
    path: '/attempts/$attemptId',
    getParentRoute: () => AuthenticatedAdminExamsExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/books': typeof AuthenticatedBooksRouteWithChildren
  '/bundles': typeof AuthenticatedBundlesRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/api/chatbot': typeof ApiChatbotRoute
  '/api/rpc': typeof ApiRpcRoute
  '/grades/$gradeKey': typeof GradesGradeKeyRoute
  '/admin/ai-faq': typeof AuthenticatedAdminAiFaqRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/admin/assistants': typeof AuthenticatedAdminAssistantsRoute
  '/admin/book-orders': typeof AuthenticatedAdminBookOrdersRoute
  '/admin/books': typeof AuthenticatedAdminBooksRoute
  '/admin/bundles': typeof AuthenticatedAdminBundlesRoute
  '/admin/centers': typeof AuthenticatedAdminCentersRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/admin/homework': typeof AuthenticatedAdminHomeworkRouteWithChildren
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/lectures': typeof AuthenticatedAdminLecturesRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/admin/login-audit': typeof AuthenticatedAdminLoginAuditRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/personal-exams': typeof AuthenticatedAdminPersonalExamsRoute
  '/admin/qna': typeof AuthenticatedAdminQnaRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRouteWithChildren
  '/admin/recharge-codes': typeof AuthenticatedAdminRechargeCodesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-content': typeof AuthenticatedAdminSiteContentRoute
  '/admin/student-results': typeof AuthenticatedAdminStudentResultsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/viewing': typeof AuthenticatedAdminViewingRoute
  '/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRouteWithChildren
  '/exams/$examId': typeof AuthenticatedExamsExamIdRouteWithChildren
  '/homework/$homeworkId': typeof AuthenticatedHomeworkHomeworkIdRoute
  '/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/practice/mistakes': typeof AuthenticatedPracticeMistakesRoute
  '/api/payment/review': typeof ApiPaymentReviewRoute
  '/api/payment/submit': typeof ApiPaymentSubmitRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRouteWithChildren
  '/admin/exams/new': typeof AuthenticatedAdminExamsNewRoute
  '/admin/homework/$homeworkId': typeof AuthenticatedAdminHomeworkHomeworkIdRoute
  '/admin/homework/new': typeof AuthenticatedAdminHomeworkNewRoute
  '/admin/questions/new': typeof AuthenticatedAdminQuestionsNewRoute
  '/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/exams/$examId/result': typeof AuthenticatedExamsExamIdResultRoute
  '/courses/$courseId/lectures/$lectureId': typeof AuthenticatedCoursesCourseIdLecturesLectureIdRoute
  '/courses/$courseId/lessons/$lessonId': typeof AuthenticatedCoursesCourseIdLessonsLessonIdRoute
  '/admin/exams/$examId/attempts/$attemptId': typeof AuthenticatedAdminExamsExamIdAttemptsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/books': typeof AuthenticatedBooksRouteWithChildren
  '/bundles': typeof AuthenticatedBundlesRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/api/chatbot': typeof ApiChatbotRoute
  '/api/rpc': typeof ApiRpcRoute
  '/grades/$gradeKey': typeof GradesGradeKeyRoute
  '/admin/ai-faq': typeof AuthenticatedAdminAiFaqRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/admin/assistants': typeof AuthenticatedAdminAssistantsRoute
  '/admin/book-orders': typeof AuthenticatedAdminBookOrdersRoute
  '/admin/books': typeof AuthenticatedAdminBooksRoute
  '/admin/bundles': typeof AuthenticatedAdminBundlesRoute
  '/admin/centers': typeof AuthenticatedAdminCentersRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/admin/homework': typeof AuthenticatedAdminHomeworkRouteWithChildren
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/lectures': typeof AuthenticatedAdminLecturesRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/admin/login-audit': typeof AuthenticatedAdminLoginAuditRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/personal-exams': typeof AuthenticatedAdminPersonalExamsRoute
  '/admin/qna': typeof AuthenticatedAdminQnaRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRouteWithChildren
  '/admin/recharge-codes': typeof AuthenticatedAdminRechargeCodesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/site-content': typeof AuthenticatedAdminSiteContentRoute
  '/admin/student-results': typeof AuthenticatedAdminStudentResultsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/viewing': typeof AuthenticatedAdminViewingRoute
  '/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRouteWithChildren
  '/exams/$examId': typeof AuthenticatedExamsExamIdRouteWithChildren
  '/homework/$homeworkId': typeof AuthenticatedHomeworkHomeworkIdRoute
  '/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/practice/mistakes': typeof AuthenticatedPracticeMistakesRoute
  '/api/payment/review': typeof ApiPaymentReviewRoute
  '/api/payment/submit': typeof ApiPaymentSubmitRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRouteWithChildren
  '/admin/exams/new': typeof AuthenticatedAdminExamsNewRoute
  '/admin/homework/$homeworkId': typeof AuthenticatedAdminHomeworkHomeworkIdRoute
  '/admin/homework/new': typeof AuthenticatedAdminHomeworkNewRoute
  '/admin/questions/new': typeof AuthenticatedAdminQuestionsNewRoute
  '/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/exams/$examId/result': typeof AuthenticatedExamsExamIdResultRoute
  '/courses/$courseId/lectures/$lectureId': typeof AuthenticatedCoursesCourseIdLecturesLectureIdRoute
  '/courses/$courseId/lessons/$lessonId': typeof AuthenticatedCoursesCourseIdLessonsLessonIdRoute
  '/admin/exams/$examId/attempts/$attemptId': typeof AuthenticatedAdminExamsExamIdAttemptsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/books': typeof AuthenticatedBooksRouteWithChildren
  '/_authenticated/bundles': typeof AuthenticatedBundlesRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRouteWithChildren
  '/api/chatbot': typeof ApiChatbotRoute
  '/api/rpc': typeof ApiRpcRoute
  '/grades/$gradeKey': typeof GradesGradeKeyRoute
  '/_authenticated/admin/ai-faq': typeof AuthenticatedAdminAiFaqRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/assessments': typeof AuthenticatedAdminAssessmentsRoute
  '/_authenticated/admin/assistants': typeof AuthenticatedAdminAssistantsRoute
  '/_authenticated/admin/book-orders': typeof AuthenticatedAdminBookOrdersRoute
  '/_authenticated/admin/books': typeof AuthenticatedAdminBooksRoute
  '/_authenticated/admin/bundles': typeof AuthenticatedAdminBundlesRoute
  '/_authenticated/admin/centers': typeof AuthenticatedAdminCentersRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/_authenticated/admin/homework': typeof AuthenticatedAdminHomeworkRouteWithChildren
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/lectures': typeof AuthenticatedAdminLecturesRoute
  '/_authenticated/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/_authenticated/admin/login-audit': typeof AuthenticatedAdminLoginAuditRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/personal-exams': typeof AuthenticatedAdminPersonalExamsRoute
  '/_authenticated/admin/qna': typeof AuthenticatedAdminQnaRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRouteWithChildren
  '/_authenticated/admin/recharge-codes': typeof AuthenticatedAdminRechargeCodesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/site-content': typeof AuthenticatedAdminSiteContentRoute
  '/_authenticated/admin/student-results': typeof AuthenticatedAdminStudentResultsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/viewing': typeof AuthenticatedAdminViewingRoute
  '/_authenticated/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/_authenticated/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRouteWithChildren
  '/_authenticated/exams/$examId': typeof AuthenticatedExamsExamIdRouteWithChildren
  '/_authenticated/homework/$homeworkId': typeof AuthenticatedHomeworkHomeworkIdRoute
  '/_authenticated/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/_authenticated/practice/mistakes': typeof AuthenticatedPracticeMistakesRoute
  '/api/payment/review': typeof ApiPaymentReviewRoute
  '/api/payment/submit': typeof ApiPaymentSubmitRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/_authenticated/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRouteWithChildren
  '/_authenticated/admin/exams/new': typeof AuthenticatedAdminExamsNewRoute
  '/_authenticated/admin/homework/$homeworkId': typeof AuthenticatedAdminHomeworkHomeworkIdRoute
  '/_authenticated/admin/homework/new': typeof AuthenticatedAdminHomeworkNewRoute
  '/_authenticated/admin/questions/new': typeof AuthenticatedAdminQuestionsNewRoute
  '/_authenticated/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/_authenticated/exams/$examId/result': typeof AuthenticatedExamsExamIdResultRoute
  '/_authenticated/courses/$courseId/lectures/$lectureId': typeof AuthenticatedCoursesCourseIdLecturesLectureIdRoute
  '/_authenticated/courses/$courseId/lessons/$lessonId': typeof AuthenticatedCoursesCourseIdLessonsLessonIdRoute
  '/_authenticated/admin/exams/$examId/attempts/$attemptId': typeof AuthenticatedAdminExamsExamIdAttemptsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending'
    | '/register'
    | '/search'
    | '/admin'
    | '/books'
    | '/bundles'
    | '/courses'
    | '/dashboard'
    | '/exams'
    | '/api/chatbot'
    | '/api/rpc'
    | '/grades/$gradeKey'
    | '/admin/ai-faq'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/assessments'
    | '/admin/assistants'
    | '/admin/book-orders'
    | '/admin/books'
    | '/admin/bundles'
    | '/admin/centers'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/exams'
    | '/admin/homework'
    | '/admin/invoices'
    | '/admin/lectures'
    | '/admin/lessons'
    | '/admin/login-audit'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/personal-exams'
    | '/admin/qna'
    | '/admin/questions'
    | '/admin/recharge-codes'
    | '/admin/settings'
    | '/admin/site-content'
    | '/admin/student-results'
    | '/admin/students'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/viewing'
    | '/admin/wallet'
    | '/books/$bookId'
    | '/courses/$courseId'
    | '/exams/$examId'
    | '/homework/$homeworkId'
    | '/payments/new'
    | '/practice/mistakes'
    | '/api/payment/review'
    | '/api/payment/submit'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/homework/$homeworkId'
    | '/admin/homework/new'
    | '/admin/questions/new'
    | '/admin/students/$studentId'
    | '/exams/$examId/result'
    | '/courses/$courseId/lectures/$lectureId'
    | '/courses/$courseId/lessons/$lessonId'
    | '/admin/exams/$examId/attempts/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending'
    | '/register'
    | '/search'
    | '/books'
    | '/bundles'
    | '/courses'
    | '/dashboard'
    | '/exams'
    | '/api/chatbot'
    | '/api/rpc'
    | '/grades/$gradeKey'
    | '/admin/ai-faq'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/assessments'
    | '/admin/assistants'
    | '/admin/book-orders'
    | '/admin/books'
    | '/admin/bundles'
    | '/admin/centers'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/exams'
    | '/admin/homework'
    | '/admin/invoices'
    | '/admin/lectures'
    | '/admin/lessons'
    | '/admin/login-audit'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/personal-exams'
    | '/admin/qna'
    | '/admin/questions'
    | '/admin/recharge-codes'
    | '/admin/settings'
    | '/admin/site-content'
    | '/admin/student-results'
    | '/admin/students'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/viewing'
    | '/admin/wallet'
    | '/books/$bookId'
    | '/courses/$courseId'
    | '/exams/$examId'
    | '/homework/$homeworkId'
    | '/payments/new'
    | '/practice/mistakes'
    | '/api/payment/review'
    | '/api/payment/submit'
    | '/admin'
    | '/admin/courses/$courseId'
    | '/admin/exams/$examId'
    | '/admin/exams/new'
    | '/admin/homework/$homeworkId'
    | '/admin/homework/new'
    | '/admin/questions/new'
    | '/admin/students/$studentId'
    | '/exams/$examId/result'
    | '/courses/$courseId/lectures/$lectureId'
    | '/courses/$courseId/lessons/$lessonId'
    | '/admin/exams/$examId/attempts/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pending'
    | '/register'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/books'
    | '/_authenticated/bundles'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/exams'
    | '/api/chatbot'
    | '/api/rpc'
    | '/grades/$gradeKey'
    | '/_authenticated/admin/ai-faq'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/assessments'
    | '/_authenticated/admin/assistants'
    | '/_authenticated/admin/book-orders'
    | '/_authenticated/admin/books'
    | '/_authenticated/admin/bundles'
    | '/_authenticated/admin/centers'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/homework'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/lectures'
    | '/_authenticated/admin/lessons'
    | '/_authenticated/admin/login-audit'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/personal-exams'
    | '/_authenticated/admin/qna'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/recharge-codes'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/site-content'
    | '/_authenticated/admin/student-results'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/viewing'
    | '/_authenticated/admin/wallet'
    | '/_authenticated/books/$bookId'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/exams/$examId'
    | '/_authenticated/homework/$homeworkId'
    | '/_authenticated/payments/new'
    | '/_authenticated/practice/mistakes'
    | '/api/payment/review'
    | '/api/payment/submit'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/courses/$courseId'
    | '/_authenticated/admin/exams/$examId'
    | '/_authenticated/admin/exams/new'
    | '/_authenticated/admin/homework/$homeworkId'
    | '/_authenticated/admin/homework/new'
    | '/_authenticated/admin/questions/new'
    | '/_authenticated/admin/students/$studentId'
    | '/_authenticated/exams/$examId/result'
    | '/_authenticated/courses/$courseId/lectures/$lectureId'
    | '/_authenticated/courses/$courseId/lessons/$lessonId'
    | '/_authenticated/admin/exams/$examId/attempts/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  ApiChatbotRoute: typeof ApiChatbotRoute
  ApiRpcRoute: typeof ApiRpcRoute
  GradesGradeKeyRoute: typeof GradesGradeKeyRoute
  ApiPaymentReviewRoute: typeof ApiPaymentReviewRoute
  ApiPaymentSubmitRoute: typeof ApiPaymentSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/$gradeKey': {
      id: '/grades/$gradeKey'
      path: '/grades/$gradeKey'
      fullPath: '/grades/$gradeKey'
      preLoaderRoute: typeof GradesGradeKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc': {
      id: '/api/rpc'
      path: '/api/rpc'
      fullPath: '/api/rpc'
      preLoaderRoute: typeof ApiRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatbot': {
      id: '/api/chatbot'
      path: '/api/chatbot'
      fullPath: '/api/chatbot'
      preLoaderRoute: typeof ApiChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bundles': {
      id: '/_authenticated/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof AuthenticatedBundlesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/books': {
      id: '/_authenticated/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthenticatedBooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/payment/submit': {
      id: '/api/payment/submit'
      path: '/api/payment/submit'
      fullPath: '/api/payment/submit'
      preLoaderRoute: typeof ApiPaymentSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/review': {
      id: '/api/payment/review'
      path: '/api/payment/review'
      fullPath: '/api/payment/review'
      preLoaderRoute: typeof ApiPaymentReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/practice/mistakes': {
      id: '/_authenticated/practice/mistakes'
      path: '/practice/mistakes'
      fullPath: '/practice/mistakes'
      preLoaderRoute: typeof AuthenticatedPracticeMistakesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments/new': {
      id: '/_authenticated/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof AuthenticatedPaymentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/homework/$homeworkId': {
      id: '/_authenticated/homework/$homeworkId'
      path: '/homework/$homeworkId'
      fullPath: '/homework/$homeworkId'
      preLoaderRoute: typeof AuthenticatedHomeworkHomeworkIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/$examId': {
      id: '/_authenticated/exams/$examId'
      path: '/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AuthenticatedExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
    '/_authenticated/books/$bookId': {
      id: '/_authenticated/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthenticatedBooksBookIdRouteImport
      parentRoute: typeof AuthenticatedBooksRoute
    }
    '/_authenticated/admin/wallet': {
      id: '/_authenticated/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AuthenticatedAdminWalletRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/viewing': {
      id: '/_authenticated/admin/viewing'
      path: '/viewing'
      fullPath: '/admin/viewing'
      preLoaderRoute: typeof AuthenticatedAdminViewingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/student-results': {
      id: '/_authenticated/admin/student-results'
      path: '/student-results'
      fullPath: '/admin/student-results'
      preLoaderRoute: typeof AuthenticatedAdminStudentResultsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/site-content': {
      id: '/_authenticated/admin/site-content'
      path: '/site-content'
      fullPath: '/admin/site-content'
      preLoaderRoute: typeof AuthenticatedAdminSiteContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recharge-codes': {
      id: '/_authenticated/admin/recharge-codes'
      path: '/recharge-codes'
      fullPath: '/admin/recharge-codes'
      preLoaderRoute: typeof AuthenticatedAdminRechargeCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/qna': {
      id: '/_authenticated/admin/qna'
      path: '/qna'
      fullPath: '/admin/qna'
      preLoaderRoute: typeof AuthenticatedAdminQnaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/personal-exams': {
      id: '/_authenticated/admin/personal-exams'
      path: '/personal-exams'
      fullPath: '/admin/personal-exams'
      preLoaderRoute: typeof AuthenticatedAdminPersonalExamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/login-audit': {
      id: '/_authenticated/admin/login-audit'
      path: '/login-audit'
      fullPath: '/admin/login-audit'
      preLoaderRoute: typeof AuthenticatedAdminLoginAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lessons': {
      id: '/_authenticated/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AuthenticatedAdminLessonsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lectures': {
      id: '/_authenticated/admin/lectures'
      path: '/lectures'
      fullPath: '/admin/lectures'
      preLoaderRoute: typeof AuthenticatedAdminLecturesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/homework': {
      id: '/_authenticated/admin/homework'
      path: '/homework'
      fullPath: '/admin/homework'
      preLoaderRoute: typeof AuthenticatedAdminHomeworkRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/centers': {
      id: '/_authenticated/admin/centers'
      path: '/centers'
      fullPath: '/admin/centers'
      preLoaderRoute: typeof AuthenticatedAdminCentersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bundles': {
      id: '/_authenticated/admin/bundles'
      path: '/bundles'
      fullPath: '/admin/bundles'
      preLoaderRoute: typeof AuthenticatedAdminBundlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/books': {
      id: '/_authenticated/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AuthenticatedAdminBooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/book-orders': {
      id: '/_authenticated/admin/book-orders'
      path: '/book-orders'
      fullPath: '/admin/book-orders'
      preLoaderRoute: typeof AuthenticatedAdminBookOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assistants': {
      id: '/_authenticated/admin/assistants'
      path: '/assistants'
      fullPath: '/admin/assistants'
      preLoaderRoute: typeof AuthenticatedAdminAssistantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assessments': {
      id: '/_authenticated/admin/assessments'
      path: '/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AuthenticatedAdminAssessmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai-faq': {
      id: '/_authenticated/admin/ai-faq'
      path: '/ai-faq'
      fullPath: '/admin/ai-faq'
      preLoaderRoute: typeof AuthenticatedAdminAiFaqRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/exams/$examId/result': {
      id: '/_authenticated/exams/$examId/result'
      path: '/result'
      fullPath: '/exams/$examId/result'
      preLoaderRoute: typeof AuthenticatedExamsExamIdResultRouteImport
      parentRoute: typeof AuthenticatedExamsExamIdRoute
    }
    '/_authenticated/admin/students/$studentId': {
      id: '/_authenticated/admin/students/$studentId'
      path: '/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AuthenticatedAdminStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedAdminStudentsRoute
    }
    '/_authenticated/admin/questions/new': {
      id: '/_authenticated/admin/questions/new'
      path: '/new'
      fullPath: '/admin/questions/new'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsNewRouteImport
      parentRoute: typeof AuthenticatedAdminQuestionsRoute
    }
    '/_authenticated/admin/homework/new': {
      id: '/_authenticated/admin/homework/new'
      path: '/new'
      fullPath: '/admin/homework/new'
      preLoaderRoute: typeof AuthenticatedAdminHomeworkNewRouteImport
      parentRoute: typeof AuthenticatedAdminHomeworkRoute
    }
    '/_authenticated/admin/homework/$homeworkId': {
      id: '/_authenticated/admin/homework/$homeworkId'
      path: '/$homeworkId'
      fullPath: '/admin/homework/$homeworkId'
      preLoaderRoute: typeof AuthenticatedAdminHomeworkHomeworkIdRouteImport
      parentRoute: typeof AuthenticatedAdminHomeworkRoute
    }
    '/_authenticated/admin/exams/new': {
      id: '/_authenticated/admin/exams/new'
      path: '/new'
      fullPath: '/admin/exams/new'
      preLoaderRoute: typeof AuthenticatedAdminExamsNewRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
    '/_authenticated/admin/exams/$examId': {
      id: '/_authenticated/admin/exams/$examId'
      path: '/$examId'
      fullPath: '/admin/exams/$examId'
      preLoaderRoute: typeof AuthenticatedAdminExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
    '/_authenticated/admin/courses/$courseId': {
      id: '/_authenticated/admin/courses/$courseId'
      path: '/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/courses/$courseId/lessons/$lessonId': {
      id: '/_authenticated/courses/$courseId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRoute
    }
    '/_authenticated/courses/$courseId/lectures/$lectureId': {
      id: '/_authenticated/courses/$courseId/lectures/$lectureId'
      path: '/lectures/$lectureId'
      fullPath: '/courses/$courseId/lectures/$lectureId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdLecturesLectureIdRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRoute
    }
    '/_authenticated/admin/exams/$examId/attempts/$attemptId': {
      id: '/_authenticated/admin/exams/$examId/attempts/$attemptId'
      path: '/attempts/$attemptId'
      fullPath: '/admin/exams/$examId/attempts/$attemptId'
      preLoaderRoute: typeof AuthenticatedAdminExamsExamIdAttemptsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedAdminExamsExamIdRoute
    }
  }
}

interface AuthenticatedAdminCoursesRouteChildren {
  AuthenticatedAdminCoursesCourseIdRoute: typeof AuthenticatedAdminCoursesCourseIdRoute
}

const AuthenticatedAdminCoursesRouteChildren: AuthenticatedAdminCoursesRouteChildren =
  {
    AuthenticatedAdminCoursesCourseIdRoute:
      AuthenticatedAdminCoursesCourseIdRoute,
  }

const AuthenticatedAdminCoursesRouteWithChildren =
  AuthenticatedAdminCoursesRoute._addFileChildren(
    AuthenticatedAdminCoursesRouteChildren,
  )

interface AuthenticatedAdminExamsExamIdRouteChildren {
  AuthenticatedAdminExamsExamIdAttemptsAttemptIdRoute: typeof AuthenticatedAdminExamsExamIdAttemptsAttemptIdRoute
}

const AuthenticatedAdminExamsExamIdRouteChildren: AuthenticatedAdminExamsExamIdRouteChildren =
  {
    AuthenticatedAdminExamsExamIdAttemptsAttemptIdRoute:
      AuthenticatedAdminExamsExamIdAttemptsAttemptIdRoute,
  }

const AuthenticatedAdminExamsExamIdRouteWithChildren =
  AuthenticatedAdminExamsExamIdRoute._addFileChildren(
    AuthenticatedAdminExamsExamIdRouteChildren,
  )

interface AuthenticatedAdminExamsRouteChildren {
  AuthenticatedAdminExamsExamIdRoute: typeof AuthenticatedAdminExamsExamIdRouteWithChildren
  AuthenticatedAdminExamsNewRoute: typeof AuthenticatedAdminExamsNewRoute
}

const AuthenticatedAdminExamsRouteChildren: AuthenticatedAdminExamsRouteChildren =
  {
    AuthenticatedAdminExamsExamIdRoute:
      AuthenticatedAdminExamsExamIdRouteWithChildren,
    AuthenticatedAdminExamsNewRoute: AuthenticatedAdminExamsNewRoute,
  }

const AuthenticatedAdminExamsRouteWithChildren =
  AuthenticatedAdminExamsRoute._addFileChildren(
    AuthenticatedAdminExamsRouteChildren,
  )

interface AuthenticatedAdminHomeworkRouteChildren {
  AuthenticatedAdminHomeworkHomeworkIdRoute: typeof AuthenticatedAdminHomeworkHomeworkIdRoute
  AuthenticatedAdminHomeworkNewRoute: typeof AuthenticatedAdminHomeworkNewRoute
}

const AuthenticatedAdminHomeworkRouteChildren: AuthenticatedAdminHomeworkRouteChildren =
  {
    AuthenticatedAdminHomeworkHomeworkIdRoute:
      AuthenticatedAdminHomeworkHomeworkIdRoute,
    AuthenticatedAdminHomeworkNewRoute: AuthenticatedAdminHomeworkNewRoute,
  }

const AuthenticatedAdminHomeworkRouteWithChildren =
  AuthenticatedAdminHomeworkRoute._addFileChildren(
    AuthenticatedAdminHomeworkRouteChildren,
  )

interface AuthenticatedAdminQuestionsRouteChildren {
  AuthenticatedAdminQuestionsNewRoute: typeof AuthenticatedAdminQuestionsNewRoute
}

const AuthenticatedAdminQuestionsRouteChildren: AuthenticatedAdminQuestionsRouteChildren =
  {
    AuthenticatedAdminQuestionsNewRoute: AuthenticatedAdminQuestionsNewRoute,
  }

const AuthenticatedAdminQuestionsRouteWithChildren =
  AuthenticatedAdminQuestionsRoute._addFileChildren(
    AuthenticatedAdminQuestionsRouteChildren,
  )

interface AuthenticatedAdminStudentsRouteChildren {
  AuthenticatedAdminStudentsStudentIdRoute: typeof AuthenticatedAdminStudentsStudentIdRoute
}

const AuthenticatedAdminStudentsRouteChildren: AuthenticatedAdminStudentsRouteChildren =
  {
    AuthenticatedAdminStudentsStudentIdRoute:
      AuthenticatedAdminStudentsStudentIdRoute,
  }

const AuthenticatedAdminStudentsRouteWithChildren =
  AuthenticatedAdminStudentsRoute._addFileChildren(
    AuthenticatedAdminStudentsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiFaqRoute: typeof AuthenticatedAdminAiFaqRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminAssessmentsRoute: typeof AuthenticatedAdminAssessmentsRoute
  AuthenticatedAdminAssistantsRoute: typeof AuthenticatedAdminAssistantsRoute
  AuthenticatedAdminBookOrdersRoute: typeof AuthenticatedAdminBookOrdersRoute
  AuthenticatedAdminBooksRoute: typeof AuthenticatedAdminBooksRoute
  AuthenticatedAdminBundlesRoute: typeof AuthenticatedAdminBundlesRoute
  AuthenticatedAdminCentersRoute: typeof AuthenticatedAdminCentersRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRouteWithChildren
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRouteWithChildren
  AuthenticatedAdminHomeworkRoute: typeof AuthenticatedAdminHomeworkRouteWithChildren
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminLecturesRoute: typeof AuthenticatedAdminLecturesRoute
  AuthenticatedAdminLessonsRoute: typeof AuthenticatedAdminLessonsRoute
  AuthenticatedAdminLoginAuditRoute: typeof AuthenticatedAdminLoginAuditRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPersonalExamsRoute: typeof AuthenticatedAdminPersonalExamsRoute
  AuthenticatedAdminQnaRoute: typeof AuthenticatedAdminQnaRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRouteWithChildren
  AuthenticatedAdminRechargeCodesRoute: typeof AuthenticatedAdminRechargeCodesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSiteContentRoute: typeof AuthenticatedAdminSiteContentRoute
  AuthenticatedAdminStudentResultsRoute: typeof AuthenticatedAdminStudentResultsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRouteWithChildren
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminViewingRoute: typeof AuthenticatedAdminViewingRoute
  AuthenticatedAdminWalletRoute: typeof AuthenticatedAdminWalletRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiFaqRoute: AuthenticatedAdminAiFaqRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminAssessmentsRoute: AuthenticatedAdminAssessmentsRoute,
  AuthenticatedAdminAssistantsRoute: AuthenticatedAdminAssistantsRoute,
  AuthenticatedAdminBookOrdersRoute: AuthenticatedAdminBookOrdersRoute,
  AuthenticatedAdminBooksRoute: AuthenticatedAdminBooksRoute,
  AuthenticatedAdminBundlesRoute: AuthenticatedAdminBundlesRoute,
  AuthenticatedAdminCentersRoute: AuthenticatedAdminCentersRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRouteWithChildren,
  AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRouteWithChildren,
  AuthenticatedAdminHomeworkRoute: AuthenticatedAdminHomeworkRouteWithChildren,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminLecturesRoute: AuthenticatedAdminLecturesRoute,
  AuthenticatedAdminLessonsRoute: AuthenticatedAdminLessonsRoute,
  AuthenticatedAdminLoginAuditRoute: AuthenticatedAdminLoginAuditRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPersonalExamsRoute: AuthenticatedAdminPersonalExamsRoute,
  AuthenticatedAdminQnaRoute: AuthenticatedAdminQnaRoute,
  AuthenticatedAdminQuestionsRoute:
    AuthenticatedAdminQuestionsRouteWithChildren,
  AuthenticatedAdminRechargeCodesRoute: AuthenticatedAdminRechargeCodesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSiteContentRoute: AuthenticatedAdminSiteContentRoute,
  AuthenticatedAdminStudentResultsRoute: AuthenticatedAdminStudentResultsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRouteWithChildren,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminViewingRoute: AuthenticatedAdminViewingRoute,
  AuthenticatedAdminWalletRoute: AuthenticatedAdminWalletRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBooksRouteChildren {
  AuthenticatedBooksBookIdRoute: typeof AuthenticatedBooksBookIdRoute
}

const AuthenticatedBooksRouteChildren: AuthenticatedBooksRouteChildren = {
  AuthenticatedBooksBookIdRoute: AuthenticatedBooksBookIdRoute,
}

const AuthenticatedBooksRouteWithChildren =
  AuthenticatedBooksRoute._addFileChildren(AuthenticatedBooksRouteChildren)

interface AuthenticatedCoursesCourseIdRouteChildren {
  AuthenticatedCoursesCourseIdLecturesLectureIdRoute: typeof AuthenticatedCoursesCourseIdLecturesLectureIdRoute
  AuthenticatedCoursesCourseIdLessonsLessonIdRoute: typeof AuthenticatedCoursesCourseIdLessonsLessonIdRoute
}

const AuthenticatedCoursesCourseIdRouteChildren: AuthenticatedCoursesCourseIdRouteChildren =
  {
    AuthenticatedCoursesCourseIdLecturesLectureIdRoute:
      AuthenticatedCoursesCourseIdLecturesLectureIdRoute,
    AuthenticatedCoursesCourseIdLessonsLessonIdRoute:
      AuthenticatedCoursesCourseIdLessonsLessonIdRoute,
  }

const AuthenticatedCoursesCourseIdRouteWithChildren =
  AuthenticatedCoursesCourseIdRoute._addFileChildren(
    AuthenticatedCoursesCourseIdRouteChildren,
  )

interface AuthenticatedCoursesRouteChildren {
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRouteWithChildren
}

const AuthenticatedCoursesRouteChildren: AuthenticatedCoursesRouteChildren = {
  AuthenticatedCoursesCourseIdRoute:
    AuthenticatedCoursesCourseIdRouteWithChildren,
}

const AuthenticatedCoursesRouteWithChildren =
  AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren)

interface AuthenticatedExamsExamIdRouteChildren {
  AuthenticatedExamsExamIdResultRoute: typeof AuthenticatedExamsExamIdResultRoute
}

const AuthenticatedExamsExamIdRouteChildren: AuthenticatedExamsExamIdRouteChildren =
  {
    AuthenticatedExamsExamIdResultRoute: AuthenticatedExamsExamIdResultRoute,
  }

const AuthenticatedExamsExamIdRouteWithChildren =
  AuthenticatedExamsExamIdRoute._addFileChildren(
    AuthenticatedExamsExamIdRouteChildren,
  )

interface AuthenticatedExamsRouteChildren {
  AuthenticatedExamsExamIdRoute: typeof AuthenticatedExamsExamIdRouteWithChildren
}

const AuthenticatedExamsRouteChildren: AuthenticatedExamsRouteChildren = {
  AuthenticatedExamsExamIdRoute: AuthenticatedExamsExamIdRouteWithChildren,
}

const AuthenticatedExamsRouteWithChildren =
  AuthenticatedExamsRoute._addFileChildren(AuthenticatedExamsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBooksRoute: typeof AuthenticatedBooksRouteWithChildren
  AuthenticatedBundlesRoute: typeof AuthenticatedBundlesRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRouteWithChildren
  AuthenticatedHomeworkHomeworkIdRoute: typeof AuthenticatedHomeworkHomeworkIdRoute
  AuthenticatedPaymentsNewRoute: typeof AuthenticatedPaymentsNewRoute
  AuthenticatedPracticeMistakesRoute: typeof AuthenticatedPracticeMistakesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBooksRoute: AuthenticatedBooksRouteWithChildren,
  AuthenticatedBundlesRoute: AuthenticatedBundlesRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRouteWithChildren,
  AuthenticatedHomeworkHomeworkIdRoute: AuthenticatedHomeworkHomeworkIdRoute,
  AuthenticatedPaymentsNewRoute: AuthenticatedPaymentsNewRoute,
  AuthenticatedPracticeMistakesRoute: AuthenticatedPracticeMistakesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  ApiChatbotRoute: ApiChatbotRoute,
  ApiRpcRoute: ApiRpcRoute,
  GradesGradeKeyRoute: GradesGradeKeyRoute,
  ApiPaymentReviewRoute: ApiPaymentReviewRoute,
  ApiPaymentSubmitRoute: ApiPaymentSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
